apiVersion: apps/v1
kind: Deployment
metadata:
  name: webb-ai-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webb-ai-api
  template:
    metadata:
      labels:
        app: webb-ai-api
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done']
      containers:
      - name: webb-ai-api
        image: webb-ai-api:latest
        imagePullPolicy: IfNotPresent
