// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FileStatus string

const (
	FileStatusCREATED    FileStatus = "CREATED"
	FileStatusPROCESSING FileStatus = "PROCESSING"
	FileStatusPROCESSED  FileStatus = "PROCESSED"
	FileStatusFAILED     FileStatus = "FAILED"
	FileStatusDELETED    FileStatus = "DELETED"
	FileStatusREMOVED    FileStatus = "REMOVED"
)

func (e *FileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileStatus(s)
	case string:
		*e = FileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileStatus: %T", src)
	}
	return nil
}

type NullFileStatus struct {
	FileStatus FileStatus `json:"file_status"`
	Valid      bool       `json:"valid"` // Valid is true if FileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileStatus), nil
}

type JobStatus string

const (
	JobStatusRUNNING   JobStatus = "RUNNING"
	JobStatusFAILED    JobStatus = "FAILED"
	JobStatusCOMPLETED JobStatus = "COMPLETED"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type SourceStatus string

const (
	SourceStatusSCANNING SourceStatus = "SCANNING"
	SourceStatusIDLE     SourceStatus = "IDLE"
)

func (e *SourceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceStatus(s)
	case string:
		*e = SourceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceStatus: %T", src)
	}
	return nil
}

type NullSourceStatus struct {
	SourceStatus SourceStatus `json:"source_status"`
	Valid        bool         `json:"valid"` // Valid is true if SourceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SourceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceStatus), nil
}

type SourceType string

const (
	SourceTypeS3       SourceType = "S3"
	SourceTypeONEDRIVE SourceType = "ONE_DRIVE"
)

func (e *SourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceType(s)
	case string:
		*e = SourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceType: %T", src)
	}
	return nil
}

type NullSourceType struct {
	SourceType SourceType `json:"source_type"`
	Valid      bool       `json:"valid"` // Valid is true if SourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.SourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceType), nil
}

type Chat struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
}

type ChatMessage struct {
	ID           uuid.UUID `json:"id"`
	ChatID       uuid.UUID `json:"chat_id"`
	Content      string    `json:"content"`
	IsAiResponse bool      `json:"is_ai_response"`
	CreatedAt    time.Time `json:"created_at"`
}

type File struct {
	ID              uuid.UUID          `json:"id"`
	SourceID        uuid.UUID          `json:"source_id"`
	Url             string             `json:"url"`
	Status          FileStatus         `json:"status"`
	LastProcessedAt pgtype.Timestamptz `json:"last_processed_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type OnedriveSource struct {
	ID           uuid.UUID    `json:"id"`
	Name         string       `json:"name"`
	Description  pgtype.Text  `json:"description"`
	Type         SourceType   `json:"type"`
	Status       SourceStatus `json:"status"`
	SecretsStore string       `json:"secrets_store"`
	CreatedAt    time.Time    `json:"created_at"`
	SourceType   string       `json:"source_type"`
	TenantID     string       `json:"tenant_id"`
}

type S3Source struct {
	ID           uuid.UUID    `json:"id"`
	Name         string       `json:"name"`
	Description  pgtype.Text  `json:"description"`
	Type         SourceType   `json:"type"`
	Status       SourceStatus `json:"status"`
	SecretsStore string       `json:"secrets_store"`
	CreatedAt    time.Time    `json:"created_at"`
	SourceType   string       `json:"source_type"`
	BucketName   string       `json:"bucket_name"`
	Region       string       `json:"region"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Source struct {
	ID           uuid.UUID    `json:"id"`
	Name         string       `json:"name"`
	Description  pgtype.Text  `json:"description"`
	Type         SourceType   `json:"type"`
	Status       SourceStatus `json:"status"`
	SecretsStore string       `json:"secrets_store"`
	CreatedAt    time.Time    `json:"created_at"`
}

type SourceJob struct {
	ID        uuid.UUID `json:"id"`
	SourceID  uuid.UUID `json:"source_id"`
	Status    JobStatus `json:"status"`
	FileCount int32     `json:"file_count"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type UserGroup struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type VerifyEmail struct {
	ID         uuid.UUID `json:"id"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiresAt  time.Time `json:"expires_at"`
}
