// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: service_webb_ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebbAi_CreateUser_FullMethodName = "/pb.WebbAi/CreateUser"
)

// WebbAiClient is the client API for WebbAi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebbAiClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type webbAiClient struct {
	cc grpc.ClientConnInterface
}

func NewWebbAiClient(cc grpc.ClientConnInterface) WebbAiClient {
	return &webbAiClient{cc}
}

func (c *webbAiClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, WebbAi_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebbAiServer is the server API for WebbAi service.
// All implementations must embed UnimplementedWebbAiServer
// for forward compatibility.
type WebbAiServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	mustEmbedUnimplementedWebbAiServer()
}

// UnimplementedWebbAiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebbAiServer struct{}

func (UnimplementedWebbAiServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedWebbAiServer) mustEmbedUnimplementedWebbAiServer() {}
func (UnimplementedWebbAiServer) testEmbeddedByValue()                {}

// UnsafeWebbAiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebbAiServer will
// result in compilation errors.
type UnsafeWebbAiServer interface {
	mustEmbedUnimplementedWebbAiServer()
}

func RegisterWebbAiServer(s grpc.ServiceRegistrar, srv WebbAiServer) {
	// If the following call pancis, it indicates UnimplementedWebbAiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebbAi_ServiceDesc, srv)
}

func _WebbAi_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebbAiServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebbAi_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebbAiServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebbAi_ServiceDesc is the grpc.ServiceDesc for WebbAi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebbAi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WebbAi",
	HandlerType: (*WebbAiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _WebbAi_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_webb_ai.proto",
}
